### ISSUE TITLE
Wrong Power Values

### ISSUE THREAD

**Issue by jangrik** [iobroker-community-adapters/ioBroker.envertech-pv#11]
First problem:
I have two Envertech EVT300 which are reporting their values using one bridge EVB300.
The value envertech-pv.0.data.gatewayXXXXXXX.info.gateway_power_now is alterating: smotimes zero, sometimes the value of the first microinverter, sometimes the second, and sometimes as expected the sum of both.
Not to much a problem for me anymore as i identified this and calculat the sum now myself.

Small second problem: 
The config-page of the adapter-instance is somewhat broken, it shows up double. 

Otherwise a great adapter, thank a lot for your work.

**Comment by mcm1957** [comment]
Structure of states has been changed with 1.0.0 to report values just as they are reported by envertech.
If this problem still exists, please reopen or create a new issue.
