### ISSUE TITLE
	[gateway] object MGSVER not configured - report to developer.

### ISSUE THREAD

**Issue by TJHooker** [iobroker-community-adapters/ioBroker.envertech-pv#110]
<html>
<body>

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
envertech-pv.0 | 2023-09-13 15:54:31.852 | warn | [gateway] object MGSVER not configured - report to developer.

</body>
</html>

this error come  since 3:30 PM  09.13.2023  can it  be that there is temp problem  from side Envertech  be cause you APP dint change

**Comment by mcm1957** [comment]
Thanks, I check.

**Comment by mcm1957** [comment]
Short Feedback:
Problem can be reproduced. I'm working on a fix.
Envertech seems to have changed something at their protocol.

As a workaround you might set log level to error until fixed.

**Comment by mcm1957** [comment]
There's even a clean fix for this Problem:

Please DEACTIVATE the option to log not yet implemented keys. When duing this you should be able to set logging to normal (info) level again without any sideeffects: 

![image](https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/assets/28575778/46633e4e-4ded-46fc-939d-c0090ea15332)

The unknown / new keys will be implemented with the next release. Currently they look not really of interest for ioBroker - but I'll ty to check. (Protocal is not officially documented)

**Comment by mcm1957** [comment]
fixed with 1.2.0
