### ISSUE TITLE
incorrect units 

### ISSUE THREAD

**Issue by Luapsi** [iobroker-community-adapters/ioBroker.envertech-pv#113]
Units for two data fields are incorrect!

**Expected behavior**  
The unit kWh is expected in the database field “value.power.production”.
The unit w is expected in the database field "value.power"
**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 1.0.2
 - NPM version: 9.8.1 
 - Node version: v18.18.2 
 - Operating system: Windows10

![2023-10-31_160724](https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/assets/149511288/c740aff4-c9ea-4ad5-bfe4-bcc963c9bea4)

**Comment by mcm1957** [comment]
fixed with 1.1.0
