### ISSUE TITLE
Please consider adding your adapter to the offical iobroker repos

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.envertech-pv#12]
Thanks for your work and this adpter.

**Please consider adding your adapter to the offical iobroker repos

https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository**

------------

If you are not longer interested in maintaining this adapter, please let us know and consider transfering ownership iobroker-community-adapters.

Thanks
McM1957

**Comment by adcrafter27** [comment]
Hallo,
Ich werde diesen Adapter nicht mehr weiter entwickeln da ich die Daten auf einer anderen weiße auslese.
Ich habe den Adapter "noch" nicht gelöscht da doch einige ihn verwenden, aber gerne kann jemand anders an meiner stelle weitermachen und noch sicher einiges besser machen

**Comment by mcm1957** [comment]
Danke für's feedback.

Wenn du bereit wärst den Adapter in die ioBroker Community zu moven könnt ich mir anschaun was es für Probleme gibt. Hab selbst 2 Envertech Microkonvert mit EVB300 - also Testequipment im Minimalumfang.

MOve in community wäre der Vorteil, dass npm name gleich bleiben kann und damit bestehende User (zumindest geplanter Maßen) keine Unterbrechung erleiden.

Info zum move findest du hier:
https://github.com/iobroker-community-adapters/info#technical-information

Dass der Adapter (noch) nicht im latest ist sollte dich nicht vom Move abhalten - das können "wir" (ich od. ev. ein anderer Entwickler dann schon erledigen. Falls du Hilfe brauchst, bitte einfach melden. 

Mail: mcm57@gmx.at oder auf Telegram t.me/ioBroker_development (https://t.me/ioBroker_development)

**Comment by mcm1957** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/2189
