### ISSUE TITLE
Missing one envertech WR - more than 20 inverters

### ISSUE THREAD

**Issue by Bitty406** [iobroker-community-adapters/ioBroker.envertech-pv#164]
Hello everyone
I have now installed 21 envertech WR.
But only 20 are listed in the adapter (V1.2.0)?
See error message in log.
Greetings Stefan

![missing envertech](https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/assets/127534995/cc449563-66ed-4f45-9b90-04a9f69dda21)

**Comment by mcm1957** [comment]
Thanks for reporting this problem. I will take care of it.

Link to forum topic https://forum.iobroker.net/topic/73763/iobroker-envertech-wechselrichter-wird-nicht-angezeigt

**Comment by mcm1957** [comment]
closed on error ...

**Comment by mcm1957** [comment]
@Bitty406 
Please test release 1.3.2 available at npm / github now and at LTEST repository tomorrow.

**Comment by Bitty406** [comment]
V1.3.2 works
All 21 inverters are listed in the objects.
Many thanks

**Comment by mcm1957** [comment]
Fixed wirh 1.3.2
