### ISSUE TITLE
Warnmeldung  instance system.adapter.envertech-pv.0 already running with pid xxxxxx

### ISSUE THREAD

**Issue by JackDaniel007** [iobroker-community-adapters/ioBroker.envertech-pv#184]
host.NUC | 2024-06-21 08:05:31.009 | warn | instance system.adapter.envertech-pv.0 already running with pid 684413
host.NUC | 2024-06-21 08:00:32.035 | warn | instance system.adapter.envertech-pv.0 already running with pid 684413

**Comment by mcm1957** [comment]
Please add version to Info to all issues:

Adapter:
js-controller:
node:
O/S:

And please add a COMPLETE log showing the error. This log should include at least the last shutdown and startup the adapter and all messages logged by adapter and js-controller.

**Comment by JackDaniel007** [comment]
Adapter: 1.3.2
js-controller: 6.0.5
node: v20.14.0
O/S: Debian 12

es gibt sonst keine "anderen" meldungen von diesem adapter, die meldung kommt ja auch vom host
der adapter läuft auch ohne probleme, es kommen nur alle 5 minuten die meldung von oben

**Comment by mcm1957** [comment]
Der Adapter ist ein Daemon Adapter und sollte an sich dauernd laufen. Wenn es keine Meldungen über eine Beendigung des Adapters gibt sollte der auch nicht neu gestartet werden. Bitte prüfe ob du ein Restart aktiviert hast oder ein Script läuft dass versucht den Adapter zu starten.

**Comment by JackDaniel007** [comment]
danke für den schubs in die richtige richtung, es war wirklich ein restart alle 5 minuten aktiv :(
war also ein benutzerfehler, und somit erledigt
danke nochmal für die rasche hilfe

**Comment by mcm1957** [comment]
Na ja - eigentlich sollte ein restart ja gehn.auch wenn er eher sinnbefreit ist.

Muss mal checken ob ichcwas seh. Kann ja bei js-controller 6 noch was faul sein.

**Comment by JackDaniel007** [comment]
achja fast vergessen, der neustart muss drinnen sein
sonst kommt das hier -> host.NUC | 2024-07-15 14:38:19.918 | error | system.adapter.envertech-pv.0 schedule attribute missing

und irgendwann gkommen dann vom adapter keine aktualisierungen der db :( , obwohl er angeblich läuft

**Comment by mcm1957** [comment]
Bitte um einen vollständigen DEBUG log wo obige Meldung auftritt. Da der Adapter mode deamon ist die Meldung nicht zuordenvar.

**Comment by mcm1957** [comment]
Mangels neuer Information / debug log schließe ich hier mal.

Sollte das Problem nochmals / weiterhin auftreten, bitte ein neues Issue mit Versionsangaben und log auf Level DEBUG anlegen.
