### ISSUE TITLE
Adapter taucht nicht bei Iobroker auf

### ISSUE THREAD

**Issue by Reuli61** [iobroker-community-adapters/ioBroker.envertech-pv#2]
Hallo, habe den Adapter instaliert. Bei den Instanzen taucht er nicht auf. Also auch keine Einstellungen. Wie kommt man daran?

**Comment by adcrafter27** [comment]
Hast du den Adapter über github link Installiert? über npm funktioniert das noch nicht richtig

**Comment by Reuli61** [comment]
Ah ok. Wann sollte es funktionieren?

**Comment by adcrafter27** [comment]
Sobald ich den Fehler gefunden und verstanden habe, wobei es momentan zeitlich etwas schwierig ist
aber wenn du den Adapter über den github link Installiert klappt der Adapter

**Comment by rednosed007** [comment]
Is das Problem inzwischen gelöst? ich habe versucht mit  "npm install iobroker.envertech-pv" den adapter zu installieren. Es gab keine Fehlermeldung, und auch keine Erweiterungen in iobroker. Welche alternative gibt es denn adapter zu installieren.

**Comment by adcrafter27** [comment]
Hallo, nein habe mich damit leider noch nicht weiter beschäftigt bzw hatte ich auch ganz vergessen da ja der Adapter bei mir ohne Probleme läuft. werde aber die tage mal nachlesen wo der Fehler liegen kann das es nicht über npm geht

Du kannst den Adapter ganz normal über den github link installieren.
Kannst so machen wie es hier erklärt wird ab (1:12) https://youtu.be/px6po9InKDI?t=72

**Comment by rednosed007** [comment]
Hallo, es hat jetzt geklappt! Danke.

**Comment by Reuli61** [comment]
Hallo zusammen, bei mir wird es immer noch nicht als Instanz angezeigt.

Viele Grüße
Gisbert

Am Mi., 6. Jan. 2021 um 09:09 Uhr schrieb rednosed007 <
notifications@github.com>:

**Comment by rednosed007** [comment]
Stimmt, aber envertech-pv wird als adapter angezeigt. Der kann man dann installieren.

**Comment by Reuli61** [comment]
Kann aber nichts einstellen. Der Adapter wird angezeigt, aber man kommt
nicht drauf.

Am Mi., 6. Jan. 2021 um 17:19 Uhr schrieb rednosed007 <
notifications@github.com>:

**Comment by adcrafter27** [comment]
Hast du schon eine Instanz Installiert aus dem Adapter? über die 3 punkte und danach links unten auf + ?

![02](https://user-images.githubusercontent.com/15692264/103818301-89950e00-5068-11eb-9c7d-e09380aeee78.png)
![01](https://user-images.githubusercontent.com/15692264/103818302-8a2da480-5068-11eb-96bc-35af046e6692.png)

**Comment by Reuli61** [comment]
Funktioniert. Vielen Dank

Am Mi., 6. Jan. 2021 um 21:46 Uhr schrieb adcrafter27 <
notifications@github.com>:

**Comment by mcm1957** [comment]
closed as handling error
