### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.envertech-pv#4]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/adcrafter27/ioBroker.envertech-pv

- [ ] [E144] common.installedFrom field found in io-package.json. Must be removed.
- [ ] [E153] common.dependencies must contain {"js-controller": ">=1.5.8"} or {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "envertech-pv" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by mcm1957** [comment]
This will be done during release to repository processing.

**Comment by mcm1957** [comment]
fixed with 0.1.0
